---
- hosts: webservers
  become: yes
  tasks:
    - name: INSTALL APACHE2
      apt: 
        name: apache2 
        update_cache: yes 
        state: latest
 
    - name: ENABLED MOD_REWRITE
      apache2_module: 
        name: rewrite 
        state: present
      notify:
        - RESTART APACHE2

    - name: APACHE2 LISTEN ON PORT 8808
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8808" state=present
      notify:
       - RESTART APACHE2

    - name: HOME PAGE
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
      notify:
       - RESTART APACHE2

    - name: MAP PAGE
      copy:
        src: files/map.html
        dest: /var/www/html/map.html
      notify:
        - RESTART APACHE2

  handlers:
    - name: RESTART APACHE2
      service: name=apache2 state=restarted 

      
